steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - cp requirements_gcp.txt requirements.txt  # ✅ GCP용으로 복사 (추가!)

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/drawenglish-api', '.']
    secretEnv: ['API_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/drawenglish-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - drawenglish-api
      - --image
      - gcr.io/$PROJECT_ID/drawenglish-api
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --memory
      - 4Gi
      - --set-env-vars
      - SPACY_MODEL=en_core_web_trf
    secretEnv: ['API_KEY']

availableSecrets:
  secretManager:
    - versionName: projects/614338445338/secrets/OPENAI_API_KEY/versions/latest
      env: 'API_KEY'

images:
  - 'gcr.io/$PROJECT_ID/drawenglish-api'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamic_substitutions: true

timeout: 1200s
