steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/drawenglish-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/drawenglish-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - drawenglish-api
      - --image=gcr.io/$PROJECT_ID/drawenglish-api
      - --region=asia-northeast3
      - --platform=managed
      - --allow-unauthenticated
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest

