steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/drawenglish-api', '.']
    secretEnv: ['API_KEY']   # Secret Manager 관련 설정 부분

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/drawenglish-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - drawenglish-api
      - --image
      - gcr.io/$PROJECT_ID/drawenglish-api
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
    secretEnv: ['API_KEY']

availableSecrets:  # Secret Manager에 API Key 저장 설정 부분
  secretManager:
    - versionName: projects/614338445338/secrets/OPENAI_API_KEY/versions/latest
      env: 'API_KEY'  # GCP콘솔의 '보안 비밀 참조' 이름과 동일해야 함

images:
  - 'gcr.io/$PROJECT_ID/drawenglish-api'

options:
  logging: CLOUD_LOGGING_ONLY  # 이 부분이 없어도 빌드 안될 수 있음
  machineType: 'E2_HIGHCPU_8'
  dynamic_substitutions: true

timeout: 600s  # 지정하지 않을때의 기본값이 600초임
