services:
  - type: web
    name: spacy-api
    runtime: python
    buildCommand: |
      ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: SPACY_MODEL
        value: en_core_web_sm
      - key: OPENAI_API_KEY
        sync: false  # Render Secret에 등록해둘 것